name: Python CI
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: List files (для отладки)
        run: ls -la
      - name: Run Python script
        run: python factorial.py
